<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>flx</string>
	</array>
	<key>name</key>
	<string>Felix</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(fun|proc|gen|in|and|or|not|break|do|done|else|for|forall|while|upto|downto|if|elif|endif|then|struct|typedef|include|package|let|var|val|open|syntax|perform|match|with|endmatch|enum|union|regdef|class|return|object|macro|of|instance|requires|case|when|try|endtry|yield|unless)\b</string>
			<key>name</key>
			<string>keyword.control.felix</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(private|rename|use|export|type|cfun|cproc|ctor|implements|interface|method|goto|label_address|goto-indirect|inline|branch-and-link|virtual|axiom|call)\b</string>
			<key>name</key>
			<string>keyword.other.felix</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(assert|println|charset|RE2|spawn_fthread|new|caseno|reduce|code|noreturn)\b</string>
			<key>name</key>
			<string>support.function.felix</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(true|false|bool|string|int|float|double|size|array|darray|varray|list|opt|len|regex|str)\b</string>
			<key>name</key>
			<string>constant.language.felix</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\.\.\&lt;|\+|-|%|&amp;|\$|#|\*|\^|==|=|&lt;=?|&gt;=?|-&gt;|--&gt;|=&gt;|_deref|:&gt;&gt;|\*\.|\|&gt;|(?&lt;!\.)\.{2}(?!\.)</string>
			<key>name</key>
			<string>keyword.operator.felix</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((0(x|X)[0-9a-fA-F]*)|(([0-9_]+\.?[0-9_]*)|(\.[0-9_]+))((e|E)(\+|-)?[0-9_]+)?)(i8|i16|i32|i64|u8|u16|u32|u64|t|s|i|l|ll|v|ut|tu|us|su|u|ul|lu|ull|uv|uz|zu|j|ui|ju|p|up|pu|d|ud|UL|LL|ULL|F|f|D|d|L|I)?\b</string>
			<key>name</key>
			<string>constant.numeric.felix</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\'</string>
			<key>end</key>
			<string>\'</string>
			<key>name</key>
			<string>string.quoted.single.felix</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\"</string>
			<key>end</key>
			<string>\"</string>
			<key>name</key>
			<string>string.quoted.double.felix</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(c|C|q|Q|f|F|n|N)\'</string>
			<key>end</key>
			<string>\'</string>
			<key>name</key>
			<string>string.quoted.single.special.felix</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(c|C|q|Q|f|F|n|N|r|R)\"</string>
			<key>end</key>
			<string>\"</string>
			<key>name</key>
			<string>string.quoted.double.special.felix</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\'\'\'</string>
			<key>end</key>
			<string>\'\'\'</string>
			<key>name</key>
			<string>string.quoted.multiline.single.felix</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\"\"\"</string>
			<key>end</key>
			<string>\"\"\"</string>
			<key>name</key>
			<string>string.quoted.multiline.double.felix</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(c|C|q|Q|f|F|n|N)\'\'\'</string>
			<key>end</key>
			<string>\'\'\'</string>
			<key>name</key>
			<string>string.quoted.multiline.single.special.felix</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(c|C|q|Q|f|F|n|N|r|R)\"\"\"</string>
			<key>end</key>
			<string>\"\"\"</string>
			<key>name</key>
			<string>string.quoted.multiline.double.special.felix</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.felix</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>//</string>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>comment.line.double-slash.felix</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.felix</string>
	<key>uuid</key>
	<string>02b83b75-ea3d-4111-9d21-381d5d4d9adc</string>
</dict>
</plist>
